[workspace]
resolver = "3"
members = ["crates/gb-core", "crates/gb-memory"]

[workspace.dependencies]
num-derive = { version = "0.4.2", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
thiserror = { version = "2.0.12", default-features = false }
